### ISSUE TITLE
Missing device information for Moto G

### ISSUE THREAD

**Issue by slicer69** [ubports/ubuntu-touch.io#7]
When clicking on the link for the Moto G community port from the Devices page (http://ubuntu-touch.io/devices), the site displays a 404 Error page: http://ubuntu-touch.io/device/titan

Also, the Devices page does not mention the One Plus 3 and Samsung S7 devices which the newsletter mentions were ported: https://ubports.com/blog/ubports-blog-1/post/ubuntu-touch-news-desk-180304-100

**Comment by sakibikas** [comment]
Same Issue.  The moto G Titan page directs to 404.

**Comment by NeoTheThird** [comment]
We're moving that part to https://github.com/ubports/devices.ubuntu-touch.io/, so i'll close it here. It's already reported there.

**Comment by sakibikas** [comment]
OK.

Thanks for the info.

Best,
Sakib.

On 04/05/2018, Jan Sprinz <notifications@github.com> wrote:
> We're moving that part to
> https://github.com/ubports/devices.ubuntu-touch.io/, so i'll close it here.
> It's already reported there.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ubports/ubuntu-touch.io/issues/7#issuecomment-386598524


-- 
*Best regards,*
*Sakib.*

*
*
*
IMPORTANT: This e-mail and any attachments are confidential and intended
solely for the addressee and may also be privileged or exempt from
disclosure under applicable law. If you are not the addressee, or have
received this e-mail in error, please notify me immediately, delete it from
your system and do not copy, disclose or otherwise act upon any part of
this e-mail or its attachments. Internet communications are not guaranteed
to be secure or virus-free. No responsibility for any loss arising from
unauthorized access to, or interference with, any Internet communications
by any third party, or from the transmission of any viruses will be
accepted..
*
